[package]
name = "tree-sitter-verse"
description = "Verse (Unreal Engine language) grammar for tree-sitter"
version = "1.0.0"
authors = ["Unoqwy"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "verse"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/unoqwy/tree-sitter-verse"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "/LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.26.8"
